Lesson3
oINCLUDEo/SimbirCourse pull request #4
Opened 2024-11-15 20:11 UTC by oINCLUDEo

2024-11-26 08:42 UTC, DS-170 requested changes
Задание соответствует условиям. Сам гит репозиторий и ПР'ы лучше хранить в чистоте и лишние файлы не складировать. В ПР должны быть только те файлы над которыми велась работа в рамках задания и минимальный набор для запуска кода на других/удаленных  машинах.

2024-11-26 08:42 UTC, DS-170 commented on .idea/encodings.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Пакет .idea нужно убрать из ПР и добавить в gitignore (в тот что в корне. Добавить две строчки "/.idea/" и .idea/*) и почистить кэш

2024-11-26 08:42 UTC, DS-170 commented on Course.iml
>    <component name="NewModuleRootManager" inherit-compiler-output="true">
iml файлы так же можно убрать в .gitignore (*.iml)

1. git rm --cached <all_your_iml_files> to remove all of them from the remote repository.
2. Alternatively you can do a simple command to delete all the *.iml files like git ls-files | grep "\.iml$" | xargs git rm --cached
3. Commit that change using git commit -m "msg" and after that, you can see all your *.iml files as untracked files.
4. Add *.iml to your .gitignore file and commit it in a separate commit or in the same previous commit.

2024-11-26 08:42 UTC, DS-170 commented on src/dz1/Main.java
> +}
Git для корректной работы требует пустую строчку в конце каждого файла/класса. Тут интерфейс GitHub'а это подсвечивает.

2024-11-26 08:42 UTC, DS-170 commented on src/dz2/WrongLoginException.java
> +}
Строка

2024-11-26 08:42 UTC, DS-170 commented on src/dz2/WrongPasswordException.java
> +}
Строка

2024-11-26 08:42 UTC, DS-170 commented on src/dz3/Main.java
> +}
Строка

2024-12-05 17:27 UTC, merged

2024-12-09 04:27 UTC, oINCLUDEo commented on .idea/encodings.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Исправлено

2024-12-09 04:29 UTC, oINCLUDEo commented on src/dz1/Main.java
> +}
Исправлено

2024-12-09 04:30 UTC, oINCLUDEo commented on src/dz2/WrongLoginException.java
> +}
Исправлено

2024-12-09 04:30 UTC, oINCLUDEo commented on src/dz2/WrongPasswordException.java
> +}
Исправлено

2024-12-09 04:30 UTC, oINCLUDEo commented on src/dz3/Main.java
> +}
Исправлено